blueprint:
  name: Aqara H1 Double Rocker - Simple Toggle
  description: |
    Control Philips Hue lights with Aqara H1 EU double rocker switch (WS-EUK04).
    Single press left or right button to toggle the associated light on/off.
  domain: automation
  input:
    switch_action:
      name: Aqara H1 Action Sensor
      description: The action sensor or event entity for your Aqara switch
      selector:
        entity:
          domain:
            - sensor
            - event
          multiple: false
    target_light_left:
      name: Left Light
      description: Light controlled by left button
      selector:
        target:
          entity:
            - domain: light
    target_light_right:
      name: Right Light
      description: Light controlled by right button
      selector:
        target:
          entity:
            - domain: light

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input switch_action

variables:
  action: >
    {% if trigger.to_state.state is defined %}
      {{ trigger.to_state.state }}
    {% elif trigger.to_state.attributes.event_type is defined %}
      {{ trigger.to_state.attributes.event_type }}
    {% else %}
      none
    {% endif %}

action:
  - choose:
      # LEFT BUTTON - Single press: Toggle left light
      - conditions:
          - condition: template
            value_template: "{{ action == 'single_left' }}"
        sequence:
          - service: light.toggle
            target: !input target_light_left

      # RIGHT BUTTON - Single press: Toggle right light
      - conditions:
          - condition: template
            value_template: "{{ action == 'single_right' }}"
        sequence:
          - service: light.toggle
            target: !input target_light_right
