blueprint:
  name: Aqara H1 Double Rocker - Simple Toggle and Dim
  description: |
    Control Philips Hue lights with Aqara H1 EU double rocker switch (WS-EUK04).
    - Single press: Toggle light on/off
    - Double press: Cycle through brightness levels (25% → 50% → 75% → 100% → 25%...)
  domain: automation
  input:
    switch_action:
      name: Aqara H1 Action Sensor
      description: The action sensor or event entity for your Aqara switch
      selector:
        entity:
          domain:
            - sensor
            - event
          multiple: false
    target_light_left:
      name: Left Light
      description: Light controlled by left button
      selector:
        target:
          entity:
            - domain: light
    target_light_right:
      name: Right Light (Optional)
      description: Light controlled by right button (leave empty to control same light as left)
      default: {}
      selector:
        target:
          entity:
            - domain: light

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input switch_action

variables:
  action: >
    {% if trigger.to_state.state is defined %}
      {{ trigger.to_state.state }}
    {% elif trigger.to_state.attributes.event_type is defined %}
      {{ trigger.to_state.attributes.event_type }}
    {% else %}
      none
    {% endif %}
  left_light: !input target_light_left
  right_light: !input target_light_right
  use_separate_lights: "{{ right_light.entity_id is defined and right_light.entity_id | length > 0 }}"

action:
  - choose:
      # LEFT BUTTON - Single press: Toggle
      - conditions:
          - condition: template
            value_template: "{{ action == 'single_left' }}"
        sequence:
          - service: light.toggle
            target: !input target_light_left

      # LEFT BUTTON - Double press: Cycle brightness
      - conditions:
          - condition: template
            value_template: "{{ action == 'double_left' }}"
        sequence:
          - service: light.turn_on
            target: !input target_light_left
            data:
              brightness_pct: >
                {% set lights = left_light.entity_id %}
                {% if lights is string %}
                  {% set lights = [lights] %}
                {% endif %}
                {% set current = state_attr(lights[0], 'brightness') | int(0) %}
                {% set current_pct = (current / 255 * 100) | int %}
                {% if current_pct < 25 %}
                  25
                {% elif current_pct < 50 %}
                  50
                {% elif current_pct < 75 %}
                  75
                {% elif current_pct < 100 %}
                  100
                {% else %}
                  25
                {% endif %}

      # RIGHT BUTTON - Single press: Toggle
      - conditions:
          - condition: template
            value_template: "{{ action == 'single_right' }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ use_separate_lights }}"
                sequence:
                  - service: light.toggle
                    target: !input target_light_right
            default:
              - service: light.toggle
                target: !input target_light_left

      # RIGHT BUTTON - Double press: Cycle brightness
      - conditions:
          - condition: template
            value_template: "{{ action == 'double_right' }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ use_separate_lights }}"
                sequence:
                  - service: light.turn_on
                    target: !input target_light_right
                    data:
                      brightness_pct: >
                        {% set lights = right_light.entity_id %}
                        {% if lights is string %}
                          {% set lights = [lights] %}
                        {% endif %}
                        {% set current = state_attr(lights[0], 'brightness') | int(0) %}
                        {% set current_pct = (current / 255 * 100) | int %}
                        {% if current_pct < 25 %}
                          25
                        {% elif current_pct < 50 %}
                          50
                        {% elif current_pct < 75 %}
                          75
                        {% elif current_pct < 100 %}
                          100
                        {% else %}
                          25
                        {% endif %}
            default:
              - service: light.turn_on
                target: !input target_light_left
                data:
                  brightness_pct: >
                    {% set lights = left_light.entity_id %}
                    {% if lights is string %}
                      {% set lights = [lights] %}
                    {% endif %}
                    {% set current = state_attr(lights[0], 'brightness') | int(0) %}
                    {% set current_pct = (current / 255 * 100) | int %}
                    {% if current_pct < 25 %}
                      25
                    {% elif current_pct < 50 %}
                      50
                    {% elif current_pct < 75 %}
                      75
                    {% elif current_pct < 100 %}
                      100
                    {% else %}
                      25
                    {% endif %}

      # BOTH BUTTONS - Single press: Toggle all
      - conditions:
          - condition: template
            value_template: "{{ action == 'single_both' }}"
        sequence:
          - service: light.toggle
            target: !input target_light_left
          - condition: template
            value_template: "{{ use_separate_lights }}"
          - service: light.toggle
            target: !input target_light_right

      # BOTH BUTTONS - Double press: Set all to 100%
      - conditions:
          - condition: template
            value_template: "{{ action == 'double_both' }}"
        sequence:
          - service: light.turn_on
            target: !input target_light_left
            data:
              brightness_pct: 100
          - condition: template
            value_template: "{{ use_separate_lights }}"
          - service: light.turn_on
            target: !input target_light_right
            data:
              brightness_pct: 100
