blueprint:
  name: ZBMINI Switch Controls Smart Bulb (Toggle)
  description: ZBMINI switch toggles smart bulb state
  domain: automation
  input:
    zbmini_switch:
      name: ZBMINI Switch Entity
      selector:
        entity:
          domain: switch
    target_light:
      name: Smart Bulb
      selector:
        entity:
          domain: light
trigger:
  - platform: state
    entity_id: !input zbmini_switch
action:
  - service: light.toggle
    target:
      entity_id: !input target_light
mode: single
